# Generated by Django 3.2.8 on 2021-11-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
