# Generated by Django 3.2.8 on 2021-12-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_usertasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertasks',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
