# Generated by Django 3.2.8 on 2021-12-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_usertasks_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertasks',
            old_name='completed_task',
            new_name='complete',
        ),
    ]
