# Generated by Django 3.2.8 on 2021-12-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_completed_task_usertasks_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertasks',
            old_name='complete',
            new_name='completed_task',
        ),
        migrations.AlterField(
            model_name='usertasks',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
