# Generated by Django 3.2.6 on 2022-02-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheqqit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
