# Generated by Django 3.2.8 on 2021-10-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheqqit', '0002_auto_20211014_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
