# Generated by Django 3.2.6 on 2022-02-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheqqit', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
