# Generated by Django 3.2.8 on 2021-11-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheqqit', '0006_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
