# Generated by Django 3.2.8 on 2021-12-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheqqit', '0009_delete_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
